source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '11.0'

def shared_pod
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
    pod 'MagicalRecord'
    pod 'Cartography'
    pod 'AFDateHelper'
end

target 'HKKit' do
   shared_pod
end
target 'Example' do
    shared_pod
end

