source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

def shared_pod
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'SwiftyJSON'
    pod 'MagicalRecord'
    pod 'DZNEmptyDataSet'
    pod 'Cartography'
    pod 'AFDateHelper'
    pod 'ReactiveSwift', '~> 2.0'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
end

target 'HKKit' do
   shared_pod
end
target 'Example' do
    shared_pod
end
